name: ðŸ§¼ Pull Request - Cleanup Tags and Releases

on:
  delete:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      regex:
        description: "Regex to search by"
        required: false
      pr_number:
        description: "PR Number to search by"
        required: false

jobs:
  test:
    name: Cleanup Tags and Releases
    runs-on: ubuntu-latest
    steps:
      - name: Remove unused releases and tags
        uses: bitflight-devops/github-action-cleanup-releases-and-tags@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          regex: ${{ github.event.inputs.regex }}
          pr_number: ${{ github.event.inputs.pr_number }}
